const TEXT_ANIM_CONFIG = {
  staggerChars: 0.1,
  staggerIn: 0.025,
  staggerOut: 0.025,
  inY: 0,
  outY: -100,
  startY: 100,
  inBlur: "0px",
  outBlur: "10px",
  startBlur: "10px",
  easeIn: "cubic-bezier(0.098, 0.998, 0.3, 1)",
  easeOut: "cubic-bezier(0.64, 0, 0.78, 0)",
  duration: 0.3,
  github: {
    initial: {
      opacity: 1,
      blur: "0",
      rotation: 360,
      xPercent: 500,
      yPercent: -500,
      pointerEvents: "auto",
    },
    animateIn: {
      xPercent: 0,
      yPercent: 0,
      opacity: 1,
      rotation: 0,
      blur: "0px",
      duration: 1,
      ease: "power4.out",
      pointerEvents: "auto",
    },
    animateOut: {
      xPercent: 500,
      yPercent: -500,
      opacity: 1,
      rotation: 360,
      blur: "0",
      duration: 0.5,
      ease: "power4.in",
      pointerEvents: "auto",
    },
    reset: {
      opacity: 1,
      blur: "0",
      rotation: 360,
      xPercent: 500,
      yPercent: -500,
      pointerEvents: "auto",
    },
  },
};

export default TEXT_ANIM_CONFIG;